command_publisher:
  ros__parameters:
    position_tick: [0.1, 0.1, 0.2]
    velocity_tick: [0.1, 0.1, 0.1]
    yaw_tick_deg: 2.0
    force_tick: 0.01
    trajectory_none_label: "stop"
    trajectory_1_label: "run"
